language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - sudo apt-get -qq update
install:
  - cpanm --quiet --installdeps --notest .
script:
  - perl Makefile.PL
  - make
  - make dist
  - tar zxvf *.tar.gz
  - cd DSC-[0-9]*
  - perl Makefile.PL
  - make
  - make test
