Name:           perl-DSC
Version:        2.04
Release:        1%{?dist}
Summary:        DNS Statistics Presenter Perl Library
Group:          Development/Libraries/Perl

License:        BSD-3-Clause
URL:            https://www.dns-oarc.net/oarc/data/dsc
# Source needs to be generated by dist-tools/create-source-packages, see
# https://github.com/jelu/dist-tools
Source0:        %{name}_%{version}.orig.tar.gz

BuildArch:      noarch

BuildRequires:  perl
%if 0%{?suse_version} || 0%{?sle_version}
BuildRequires:  perl-macros
%else
BuildRequires:  perl-macros
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(ExtUtils::MakeMaker)
%endif
BuildRequires:  perl(Test::More)
BuildRequires:  perl(CGI)
BuildRequires:  perl(CGI::Untaint)
BuildRequires:  perl(Digest::MD5)
BuildRequires:  perl(File::NFSLock)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(Hash::Merge)
BuildRequires:  perl(IP::Country)
BuildRequires:  perl(IP::Authority)
BuildRequires:  perl(List::Util)
BuildRequires:  perl(MIME::Base64)
BuildRequires:  perl(Math::Calc::Units)
BuildRequires:  perl(Text::Template)
BuildRequires:  perl(URI::Escape)
BuildRequires:  perl(XML::Simple)
BuildRequires:  perl(Net::DNS::Resolver)
BuildRequires:  perl(Switch)
BuildRequires:  perl(HTML::Entities)

Provides:       perl(DSC)

Requires:       perl(CGI)
Requires:       perl(CGI::Untaint)
Requires:       perl(Digest::MD5)
Requires:       perl(File::NFSLock)
Requires:       perl(File::Temp)
Requires:       perl(Hash::Merge)
Requires:       perl(IP::Country)
Requires:       perl(IP::Authority)
Requires:       perl(List::Util)
Requires:       perl(MIME::Base64)
Requires:       perl(Math::Calc::Units)
Requires:       perl(Text::Template)
Requires:       perl(URI::Escape)
Requires:       perl(XML::Simple)
Requires:       perl(Net::DNS::Resolver)
Requires:       perl(Switch)
Requires:       perl(HTML::Entities)

%description
DNS Statistics Presenter (DSP) is a tool used for exploring statistics from
busy DNS servers collected by DNS Statistics Collector (DSC).  This is the
Perl library that is used to extract and graph DSC data.


%prep
%setup -q -n %{name}_%{version}


%build
%if 0%{?suse_version} || 0%{?sle_version}
%{__perl} Makefile.PL
%else
%{__perl} Makefile.PL INSTALLDIRS=vendor
%endif
make %{?_smp_mflags}


%install
%if 0%{?suse_version} || 0%{?sle_version}
%perl_make_install
find %buildroot/%_prefix -name *.bs -a -size 0 | xargs rm -f
%perl_process_packlist
%perl_gen_filelist
%else
%{__make} pure_install DESTDIR=%{buildroot}
find %{buildroot} -type f -name .packlist -delete
%{_fixperms} -c %{buildroot}
%endif


%clean
rm -rf $RPM_BUILD_ROOT


%if 0%{?suse_version} || 0%{?sle_version}
%files -f %{name}.files
%defattr(-,root,root)
%doc Changes LICENSE README.md
%else
%files
%license LICENSE
%doc Changes README.md
%{perl_vendorlib}/DSC/
%endif


%changelog
* Wed May 24 2017 Jerry Lundström <lundstrom.jerry@gmail.com> 2.04-1
- Release 2.04
  * Fix XSS in error handling.
  * Commits:
    736e29f Fix #28: HTML encode output
    1d6243b Remove execute flag on .pm's and provide DSC
    f812504 Test using Perl 5.24 on Travis
    b758f70 Add RPM spec
* Wed Dec 14 2016 Jerry Lundström <lundstrom.jerry@gmail.com> 2.03-1
- Initial package
